export const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
export const SEARCH_BLUR = 'header/SEARCH_BLUR'
export const GET_HOTKEY_LIST = 'header/GET_HOTKEY_LIST'
export const MOUSE_IN = 'header/MOUSE_IN'
export const MOUSE_OUT = 'header/MOUSE_OUT'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'